### ISSUE TITLE
Missing LICENSE plaintext

### ISSUE THREAD

**Issue by rrrlw** [stulacy/multistateutils#1]
The DESCRIPTION file for the package does list GPL (>=2) under the License section, however, the Journal of Open Source Software requires a plain-text LICENSE file with the actual contents of the license you choose (I'm guessing GPL-2 or GPL-3) within the repository.

Can check CRAN website/manual to confirm: to avoid issues when building/installing the R package, you might have to add the LICENSE file to either .Rbuildignore or .Rinstignore (once it has been added to the repo).

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/893).

**Comment by stulacy** [comment]
Added.

**Comment by rrrlw** [comment]
The GPL-3 license has been added, but it has not been filled out. See the bottom section if the plaintext license file and the [GNU website](https://www.gnu.org/licenses/gpl-howto.en.html) under the section titled "The copyright notice" for more details.

**Comment by stulacy** [comment]
I've filled it out now, let me know if there's any other aspects that need addressing.

**Comment by rrrlw** [comment]
I think you can delete the instructional text between "END OF TERMS AND CONDITIONS"  and "multistateutils:..." as well as the text after "Also add information on how to contact you..." (feel free to add an email/phone number to replace this text, if you wish).

**Comment by rrrlw** [comment]
Since the LICENSE plaintext has been added and my suggestion above is optional (the part you filled out gives sufficient information for people to know it's meant for multistateutils), I am closing this issue. (Note: I am not a lawyer by any means, so unsure about how copyright stuff works, but what you did should be sufficient to comply with JOSS policy.)
