### ISSUE TITLE
testthat causes R CMD check to fail

### ISSUE THREAD

**Issue by rrrlw** [stulacy/multistateutils#3]
The `--no-build-vignettes` option was used to allow R CMD build to succeed (see Issue #2 for more details on why R CMD build fails without that option). However R CMD check fails due to an ERROR with testthat (see screenshot below).

![testthat failure](https://user-images.githubusercontent.com/6846515/44130942-dca6b1e6-a01d-11e8-805c-c04eeb904a88.png)

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/893).

**Comment by rrrlw** [comment]
I am slightly unsure about why this test is failing, because your Travis CI build appears clean. Let me know what your thoughts are, @stulacy?

(We can look at this after Issues #1 and #2, which, when solved, might fix this)

Edit: initial testing was done on Ubuntu 18, but was not reproduced on Windows 10 machine. Could be an artifact of my machine.

**Comment by stulacy** [comment]
I've been unable to replicate this on my Debian 8 machine. It does work on Travis but that's using 14.04. I tried to test it on Ubuntu on `rhub` (16.04) but I got an error *there is no package called `flexsurv`* but I cannot understand why it isn't available. 

Is there another way I can test on a remote Ubuntu 18 install? I'd like to get to the bottom of this

**Comment by rrrlw** [comment]
I think `rhub` might only be installing packages in the Imports field of DESCRIPTION and `flexsurv` is in the Suggests field. I ran R CMD check multiple times on multiple machines and the above test (predict_transitions function) only failed on a subset of the runs - is there randomization involved in that test that could be causing it to fail? If so, using `set.seed` to ensure reproducibility might be a good fix (although I would still be worried about why a test is failing in certain conditions).

A quick note: the logical AND operator is only a single ampersand (`&`) in R instead of two (`&&`) as in the failing `testthat` statement pictured above. Could that be a source of error?

**Comment by stulacy** [comment]
I've identified 2 causes of the issue: the use of `&&` and that the test was comparing relative error to a reference estimate, rather than absolute. I've corrected these now so it is testing the intended measure and should run for you.

**Comment by rrrlw** [comment]
Great! R CMD build and R CMD check look fine (although I would suggest switching webshot to Imports instead of Suggests).
