### ISSUE TITLE
output of msprep2 is not class msdata

### ISSUE THREAD

**Issue by sdaza** [stulacy/multistateutils#8]
Thanks for your great package. 

The output of the function `msprep2` is not class `msdata` so cannot be directly used as input for functions such as `events` (`mstate` package).

Just adding like the code below will solve the problem: 

```
output = as.data.frame(output)
attr(output, "trans") = tmat
class(output) = c("msdata","data.frame")
```

**Comment by stulacy** [comment]
Thanks for bringing this to my attention, I'll have a look at this and see if it's a feature worth adding.

**Comment by stulacy** [comment]
This feature has been added in release 1.2.3 which is now on CRAN.
